  name: Code Linting Workflow

  on:
    workflow_call:
        secrets:
            GITHUB_MACHINE_TOKEN:
                required: true

  jobs:
      code-linting:
          runs-on: ubuntu-latest
          steps:
              - name: Pull code
                uses: actions/checkout@v3
              uses: deliowales/reusable-workflows/.github/workflows/node/configure-node-workflow.yml@master
                secrets:
                  GITHUB_MACHINE_TOKEN: ${{ secrets.MACHINE_TOKEN }}
              - name: Lint
                run: npm run lint