name: Configure Node

on:
  workflow_call:
    secrets:
      GITHUB_MACHINE_TOKEN:
        required: true

jobs:
  configure-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          rm -rf .npmrc
          echo "@deliowales:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_MACHINE_TOKEN }}" >> .npmrc