name: Cluster Security Workflow

on:
  workflow_call:
    inputs:
      ENDPOINT:
        required: true
        type: string
      REMOTE_DOCKER_IMAGE:
        required: true
        type: string
    secrets:
      STACKROX_REPO_USERNAME:
        required: true
      STACKROX_REPO_PASSWORD:
        required: true

jobs:
  cluster-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -O https://mirror.openshift.com/pub/rhacs/assets/3.66.1/bin/Linux/roxctl &&
          chmod +x roxctl &&
          sudo mv roxctl /usr/local/bin
      - run: roxctl image check --endpoint "${{ inputs.ENDPOINT }}" --image "${{ inputs.REMOTE_DOCKER_IMAGE }}"
