name: Docker Lint Workflow

on:
  workflow_call:

jobs:
  docker-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Lint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning