name: Helm Linting Workflow

on:
  workflow_call:
    inputs:
      VALUES_FILE:
        type: string
        required: true

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: template
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: mkdir kubelinttest && helm template event -f ./helm/${{ inputs.VALUES_FILE }} ./helm --set releaseVersion=kubelinttesting > kubelinttest/deployment.yaml
      - name: Scan yamls
        id: kube-lint-scan
        uses: stackrox/kube-linter-action@v1
        with:
          directory: kubelinttest